homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('magic/', views.magic, name='magic'),
    path('time/<str:timeChange>', views.time, name='time'),
    path('time', views.time, name='time'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story1', include('story1.urls')),
]

story1/urls.py
from django.urls import path
from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='story1'),
    
]

homepage/models.py
from django.db import models

# Create your models here.

story1/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
import datetime

# Create your views here.

def index(request):
    return render(request, 'index.html')

def magic(request):
    return render(request, 'magic.html', {"magic": True})

def time(request, timeChange = "0"):
    timeChange = int(timeChange)

    # +7 to make the time format GMT+7
    time = datetime.datetime.now() + datetime.timedelta(hours = timeChange + 7)

    return render(request, 'time.html', {"finalTime" : time, "magic" : True})

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1.html')

homepage/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700&display=swap" rel="stylesheet">

  </head>

  <body>
      {% include 'includes/navbar.html' %}

      {% block body %}

      {% endblock %}

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

      <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>'
      <script>
          var typed = new Typed('.typed', {
              strings: ['Hi Fella, I\'m Jeremy Victor. <br/> Wanna know more? <br/> Scroll up', 'Hi Fella, I\'m Jeremy Victor. <br/> Wanna know more? <br/> Scroll down'],
              smartBackspace: true, // Default value
              typeSpeed: 50
          });
      </script>
  </body>
</html>

homepage/templates/includes/navbar.html
<div id = "navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'homepage:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto">

                {% if magic != True %}
                    <li class="nav-item active">
                        <a class="nav-link" href="#education">Education <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="#experience">Experience <span class="sr-only">(current)</span></a>
                    </li>
                    
                    <li class="nav-item active">
                        <a class="nav-link" href="#hobby">Hobby <span class="sr-only">(current)</span></a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="#contact">Contact <span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}

                    <li class="nav-item disabled">
                        <a class="nav-link" href="{% url 'homepage:magic' %}">Magic <span class="sr-only">(current)</span></a>
                    </li>

                    <span class="nav-item disabled">
                        <a class="nav-link" href="{% url 'story1:story1' %}">Story 1 <span class="sr-only">(current)</span></a>
                    </span>

                    <span class="nav-item disabled">
                        <a class="nav-link" href="{% url 'homepage:time' %}">Time <span class="sr-only">(current)</span></a>
                    </span>

                </ul>

                <!-- <span class="navbar-text">
            
                    <div class="text-center">
                        <button type="button" class="btn btn-danger align-self-center" data-toggle="modal" data-target="#exampleModal">
                            See Some Photos
                        </button>
                    </div>
                </span> -->
            </div>
        </div>    
    </nav>
</div>

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <div class="jumbotron vertical-center fluid page" id="intro">
        
        <div class="h-100 row align-item-center">

            <div class="col text-center">
                <img src="{% static 'images/fasilkom.png' %}" class="img-fluid" id="foto-profil">
                
                <div class="typed hello">
                    <span class="typed"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="jumbotron vertical-center fluid page" id="education">

        <!-- <div class="text-center">
            <h1>Education</h1>
        </div> -->

        <div class="h-100 row align-items-center">
            <div class="col">
                
                <div class="text-center educationimg">
                    <img src="{% static 'images/1.png' %}" class="rounded">
                </div>

                <h1>Elementary School</h1>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">TK Lematang Lestari</li>
                </ul>
            </div>

            <div class="col">
                <h1>Primary School</h1>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">SD Lematang Lestari</li>
                    <li class="list-group-item">SD Baptis Palembang</li>
                    <li class="list-group-item">SD Stella Marris BSD</li>
                </ul>

                <div class="text-center educationimg">
                    <img src="{% static 'images/2.png' %}" class="rounded">
                </div>

            </div>
            
            <div class="col">

                <div class="text-center educationimg">
                    <img src="{% static 'images/3.png' %}" class="rounded">
                </div>

                <h1>Junior High School</h1>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">SMP Santa Ursula BSD</li>
                </ul>
            </div>

            <div class="col">
                <h1>Senior High School</h1>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">South Tangerang 2nd High School </li>
                </ul>

                <div class="text-center educationimg">
                    <img src="{% static 'images/4.png' %}" class="rounded">
                </div>

            </div>

            
            <!-- tidak diinclude atas pertimbangan belom selesai, jadi belum bisa dianggap riwayat pendidikan

            <div class="col align-self-end">
                <h1>University</h1>
                <ul class="list-group">
                    <li class="list-group-item">University of Indonesia</li>
                </ul>

                <div class="text-center" style="margin-top: 10px;">
                    <img src="img/bem-fasilkom.png" class="rounded">
                </div>

            </div> -->


        </div>

    </div>

    <div class="jumbotron vertical-center fluid page" id="experience">

        <!-- <div class="text-center">
            <h1>Experience</h1>
        </div> -->

        <div class="h-100 row align-items-center">
            
            <table class="table table-borderless">

                <tbody>
                    <tr>
                        <td>
                            <div class="block add-img">
                                <img src="{% static 'images/bem-fasilkom.png' %}" class="img-fluid">
                            </div>
                        </td>
                        
                        <td>
                            <div class="block">
                                <p class="text-center display-4" style="font-family: allerta;">Visual Design Staff at Runtime Error 4.0<br></p>
                                <p class="text-center desc">September 2019 - November 2019</p>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="block add-img">
                                <img src="{% static 'images/perak.jpg' %}" class="img-fluid">
                            </div>
                        </td>
                        
                        <td>
                            <div class="block">
                                <p class="text-center display-4" style="font-family: allerta;">Games Division Staff at PERAK 2020<br></p>
                                <p class="text-center desc">January 2020 - Present</p>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="block add-img">
                                <img src="{% static 'images/compfest.jpg' %}" class="img-fluid">
                            </div>
                        </td>
                        
                        <td>
                            <div class="block">
                                <p class="text-center display-4" style="font-family: allerta;">Competition Staff at COMPFEST 12<br></p>
                                <p class="text-center desc">February 2020 - Present</p>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>

    <div class="jumbotron vertical-center fluid page" id="hobby">

        <!-- <div class="text-center">
            <h1>Hobby</h1>
        </div> -->

        <div class="h-100 row align-items-center">
            <table class="table table-borderless">

                <tbody>
                    <tr>
                        <td>
                            <div class="block add-img">
                                <img src="{% static 'images/music.jpg' %}" class="img-fluid">
                            </div>
                        </td>
                        
                        <td>
                            <div class="block">
                                <p class="text-left hobby-text">A wise man once said, “god created both of our ears for 1 sole reason, music.”.</p>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="block add-img">
                                <img src="{% static 'images/sport.png' %}" class="img-fluid">
                            </div>
                        </td>
                        
                        <td>
                            <div class="block">
                                <p class="text-left hobby-text">Jogging around the neighborhood in the morning? Obviously the best.</p>
                            </div>
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <div class="block add-img">
                                <img src="{% static 'images/pillow-512.png' %}" class="img-fluid">
                            </div>
                        </td>
                        
                        <td>
                            <div class="block hobby-text">
                                <p class="text-left hobby-text">Sleep after heavy work? do I really have to explain?</p>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>
    </div>


    <div class="jumbotron vertical-center fluid page" id="contact">

        <!-- <div class="text-center">
            <h1>Contact</h1>
        </div> -->

        <div class="h-100 row align-items-center">

            <div class="container">
                
                <p class="display-4">
                    Say Hello, <br>
                    <a class="text-decoration-none" href="mailto:jeremy.victor@ui.ac.id">Send me an email!</a>
                    <br><br>
                    Or check my <br>
                    <a class="text-decoration-none" href="https://www.linkedin.com/in/jeremy-victor-andre-napitupulu-975988136/">LinkedIn,</a> <br>
                    <a class="text-decoration-none" href="https://www.instagram.com/jeremyanj/">Instagram,</a> <br>
                    And <a class="text-decoration-none" href="https://twitter.com/iyejeremy">Twitter</a>. <br>
                </p>
            </div>
        </div>
    </div>

{% endblock %}

homepage/templates/magic.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <div class="jumbotron vertical-center fluid page" id="magic">
        
        <div class="h-100 row align-content-center">

            <div class="col text-center">
                <img src="{% static 'images/fasilkom.png' %}" class="img-fluid" id="foto-profil">
                
                <span class="navbar-text">
                        
                    <div class="text-center">
                        <button type="button" class="btn btn-danger align-self-center" data-toggle="modal" data-target="#exampleModal">
                            Wanna see Magic?
                        </button>
                    </div>
                </span>

                <img src="{% static 'images/fasilkom.png' %}" class="img-fluid" id="foto-profil">
            </div>
        </div>
    </div>

    <!-- Challenge 2 start here -->      
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="{% static 'images/1.png' %}" alt="First slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/2.png' %}" alt="Second slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/3.png' %}" alt="Third slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/spongebob_meme.jfif' %}" alt="Third slide">
                            </div>
                        </div>

                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>

                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>

                </div>
                <!-- <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Close</button>
                </div> -->
            </div>
        </div>
    </div>

{% endblock %}

homepage/templates/time.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <div class="jumbotron vertical-center fluid page">
        
        <div class="h-100 row align-item-center">

            <div class="col text-center">
                <img src="{% static 'images/fasilkom.png' %}" class="img-fluid" id="foto-profil">
                
                <h1>{{finalTime}}</h1>
            </div>
        </div>
    </div>


{% endblock %}

story1/templates/story1.html
<!doctype html>
{% load static %}
<html>
    <head>
        <title>Profil Saya</title>

        <!-- <link rel="stylesheet" type="text/css" href="/static/css/style.css"> -->
        
        <style>
            @import url('https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap');

            body{
                background-color: black;
                color: azure;
                margin: auto;
            }

            header{
                background-color: currentColor;
                padding: 20px;
                display: flex;
                align-items: flex-start;
            }

            div, h2{
                font-size: 25px;
                font-family: "Matrix";
            }

            table, p {
                margin: 20px;
                font-size: 25px;
                font-family: "Matrix";
            }

            td, p {
                padding: 0 20px;
            }

            #medsos ul {
                list-style-type: none;
            }

            #medsos ul li {
                float: left;
                margin: 0 5px;
            }

            #medsos ul li img {
                height: 60px;
            }

            .center{
                display: block;
                margin-left: auto;
                margin-right: auto;
                width: 50%;
            }

        </style>
        
    </head>

    <body>
        <div id="Foto">
            <img src="{% static 'images/foto.jpg' %}" class="center">
        </div>

        <div id="biodata">
            <h2>Biodata</h2>
            <table>
                <tr>
                    <td>Nama</td>
                    <td>Jeremy Victor Andre Napitupulu</td>
                </tr>

                <tr>
                    <td>NPM</td>
                    <td>1906293114</td>
                </tr>

                <tr>
                    <td>Angkatan</td>
                    <td>Maung 2019</td>
                </tr>

                <tr>
                    <td>Hobi</td>
                    <td>Menyanyi</td>
                </tr>

                <tr>
                    <td>Kuliah</td>
                    <td>Fasilkom UI</td>
                </tr>
            </table>
        </div>

        <div id="Dasar2">
            <h2>Deskripsi tentang saya</h2>
            <p>Anak bungsi di keluarga dengan 2 anak. Sejak kecil, sudah menaruh minat pada dunia informatika terutama keamanan siber. Saat SMA, mulai mengenal dunia pemrograman dan belajar algoritma khususnya competitive programming. Sejak saat itu, sudah menaruh pilihan pada jurusan informatika untuk kuliahnya.</p>
        </div>

        <div id="Riwayat">
            <h2>Riwayat Pendidikan</h2>
            <table>
                <tr>
                    <td>2004-2007</td>
                    <td>TK Lematang Lestari</td>
                </tr>

                <tr>
                    <td>2007-2010</td>
                    <td>SD Lematang Lestari</td>
                </tr>

                <tr>
                    <td>2010-2011</td>
                    <td>SD Baptis Palembang</td>
                </tr>
               
                <tr>
                    <td>2011-2013</td>
                    <td>SD Stella Marris BSD</td>
                </tr>

                <tr>
                    <td>2013-2016</td>
                    <td>SMP Santa Ursula BSD</td>
                </tr>

                <tr>
                    <td>2016-2019</td>
                    <td>SMA Negeri 2 Tangerang Selatan</td>
                </tr>

                <tr>
                    <td>2019-Sekarang</td>
                    <td>Universitas Indonesia</td>
                </tr>
            </table>
        </div>

        <div id="medsos" class="vcenter">

            <ul id="list" style="display:table; margin:0 auto;">
                <li><a target="_blank" href="https://www.linkedin.com/in/jeremy-victor-andre-napitupulu-975988136/"><img src="{% static 'images/linkedin.png' %}"></a></li>
                <li><a target="_blank" href="https://twitter.com/iyejeremy"><img src="{% static 'images/twitter.png' %}"></a></li>
                <li><a target="_blank" href="https://instagram.com/jeremyanj"><img src="{% static 'images/instagram.png' %}"></a></li>
            </ul>
        </div>
    </body>
</html>